--------------------------------------------------------
--  File created - Wednesday-July-09-2025   
--------------------------------------------------------
DROP TABLE "SYSTEM"."ADMIN";
DROP TABLE "SYSTEM"."BILL";
DROP TABLE "SYSTEM"."BOOKING";
DROP TABLE "SYSTEM"."GUEST";
DROP TABLE "SYSTEM"."BOOKING";
DROP TABLE "SYSTEM"."GUEST";
DROP TABLE "SYSTEM"."ADMIN";
DROP TABLE "SYSTEM"."BILL";
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMIN
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_ADMIN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BILL
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_BILL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOOKING
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_BOOKING"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence GUEST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."GUEST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN" 
   (	"ADMINID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BILL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BILL" 
   (	"BILLID" NUMBER, 
	"BOOKINGID" NUMBER, 
	"AMOUNT" NUMBER(10,2), 
	"ISSUEDDATE" DATE, 
	"STATUS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOOKING" 
   (	"BOOKINGID" NUMBER, 
	"GUESTID" NUMBER, 
	"ADMINID" NUMBER, 
	"CHECKINDATE" DATE, 
	"CHECKOUTDATE" DATE, 
	"NUMOFGUESTS" NUMBER, 
	"EXTRAHOURS" NUMBER, 
	"TOTALPRICE" NUMBER(10,2), 
	"PURPOSEOFSTAY" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GUEST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GUEST" 
   (	"GUESTID" NUMBER, 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"PHONENO" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"GPASSWORD" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOOKING" 
   (	"BOOKINGID" NUMBER, 
	"GUESTID" NUMBER, 
	"ADMINID" NUMBER, 
	"CHECKINDATE" DATE, 
	"CHECKOUTDATE" DATE, 
	"NUMOFGUESTS" NUMBER, 
	"EXTRAHOURS" NUMBER, 
	"TOTALPRICE" NUMBER(10,2), 
	"PURPOSEOFSTAY" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GUEST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GUEST" 
   (	"GUESTID" NUMBER, 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"PHONENO" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"GPASSWORD" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMIN" 
   (	"ADMINID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BILL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BILL" 
   (	"BILLID" NUMBER, 
	"BOOKINGID" NUMBER, 
	"AMOUNT" NUMBER(10,2), 
	"ISSUEDDATE" DATE, 
	"STATUS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ADMIN
SET DEFINE OFF;
Insert into SYSTEM.ADMIN (ADMINID,USERNAME,PASSWORD) values (1,'admin1','password123');
REM INSERTING into SYSTEM.BILL
SET DEFINE OFF;
Insert into SYSTEM.BILL (BILLID,BOOKINGID,AMOUNT,ISSUEDDATE,STATUS) values (1,1,150,to_date('16-JUN-25','DD-MON-RR'),'Telah Dibayar');
REM INSERTING into SYSTEM.BOOKING
SET DEFINE OFF;
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (1,1,1,to_date('20-JUN-25','DD-MON-RR'),to_date('22-JUN-25','DD-MON-RR'),2,1,150,'Holiday','Confirmed');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (41,5,null,to_date('05-JUL-25','DD-MON-RR'),to_date('08-JUL-25','DD-MON-RR'),2,0,250,'Business Trip','Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (42,5,null,to_date('01-AUG-25','DD-MON-RR'),to_date('03-AUG-25','DD-MON-RR'),2,null,null,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (61,7,null,to_date('07-JUL-25','DD-MON-RR'),to_date('09-JUL-25','DD-MON-RR'),3,null,null,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (62,7,null,to_date('07-JUL-25','DD-MON-RR'),to_date('09-JUL-25','DD-MON-RR'),3,null,null,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (63,7,null,to_date('07-AUG-25','DD-MON-RR'),to_date('09-AUG-25','DD-MON-RR'),4,null,null,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (64,7,null,to_date('18-JUL-25','DD-MON-RR'),to_date('19-JUL-25','DD-MON-RR'),3,0,100,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (65,9,null,to_date('09-SEP-25','DD-MON-RR'),to_date('13-SEP-25','DD-MON-RR'),4,0,400,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (66,9,null,to_date('10-JUL-25','DD-MON-RR'),to_date('11-JUL-25','DD-MON-RR'),2,0,100,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (67,9,null,to_date('12-JUL-25','DD-MON-RR'),to_date('13-JUL-25','DD-MON-RR'),4,0,100,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (68,9,null,to_date('23-JUL-25','DD-MON-RR'),to_date('24-JUL-25','DD-MON-RR'),2,2,140,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (69,9,null,to_date('30-AUG-25','DD-MON-RR'),to_date('01-SEP-25','DD-MON-RR'),10,0,200,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (70,9,null,to_date('20-JUL-25','DD-MON-RR'),to_date('22-JUL-25','DD-MON-RR'),2,0,200,null,'Menunggu Pengesahan');
Insert into SYSTEM.BOOKING (BOOKINGID,GUESTID,ADMINID,CHECKINDATE,CHECKOUTDATE,NUMOFGUESTS,EXTRAHOURS,TOTALPRICE,PURPOSEOFSTAY,STATUS) values (71,7,null,to_date('12-JUL-25','DD-MON-RR'),to_date('13-JUL-25','DD-MON-RR'),9,0,100,null,'Menunggu Pengesahan');
REM INSERTING into SYSTEM.GUEST
SET DEFINE OFF;
Insert into SYSTEM.GUEST (GUESTID,FULLNAME,PHONENO,USERNAME,GPASSWORD,EMAIL) values (1,'Ali Bin Abu','0123456789',null,null,null);
Insert into SYSTEM.GUEST (GUESTID,FULLNAME,PHONENO,USERNAME,GPASSWORD,EMAIL) values (4,'SYAHMI UZAIR BIN ABDUL HALIM','01156771012','syhm.uzr','scrypt:32768:8:1$TOYNiDOdvZxmUBf3$36bfa0be297272b08243d3c89792362de04295bbfbaea1f0003bc8d9285a0f62476904125f09c06c26dec44f2bc5b38879ea8fe8b1f8784ed12a382e7869af80','syahmiuzair2016@gmail.com');
Insert into SYSTEM.GUEST (GUESTID,FULLNAME,PHONENO,USERNAME,GPASSWORD,EMAIL) values (5,'Ali Bin Seman','01187879090','Alman','scrypt:32768:8:1$Xn5HbJFwdwKAcZcj$121d14b5d3e5765e9fa93700e4e4d898e3d863bc191977c93a5ce47ce6c1267824aa823f7face793a34e36846d57d6347df3464057e7f8ba929d10665f127c4d','aliman@gmail.com');
Insert into SYSTEM.GUEST (GUESTID,FULLNAME,PHONENO,USERNAME,GPASSWORD,EMAIL) values (6,'SHA SYAZWINA','01156777544','syazwina','scrypt:32768:8:1$cX71U3nDCEFfR5ji$9118caac0093cfe6d31e57ff9d30d5e71b364421127a9065645443908a95ba0cf8e3af36845b024c7de486fb7c5d16dfee80e034b659bd94a54c2b7007c95839','shasyaz2024@gmail.com');
Insert into SYSTEM.GUEST (GUESTID,FULLNAME,PHONENO,USERNAME,GPASSWORD,EMAIL) values (7,'Ghazali Bin Ariff','0112340987','Ghaz','scrypt:32768:8:1$adE12fBcRUzIMQ8k$b4f27acd3147727a90a607b4337ad567423031d7114cf3cd9a70a3237da03793dde98fbe8228e3f64b42b3cf333430bebc8b23642a1b05c28f1c8393488665f5','syahmiuzair2016@gmail.com');
Insert into SYSTEM.GUEST (GUESTID,FULLNAME,PHONENO,USERNAME,GPASSWORD,EMAIL) values (8,'SYAHMI UZAIR BIN ABDUL HALIM','01156771012','amad','scrypt:32768:8:1$suvUjevglS8lM6dw$e6cdbae93d152aae511e12a4af81490cd0a1c034b921cb77a4154b34de7c189ce45bb5e3a00ea2c1af7c1ecc846f527fa51538f617c11de7008e3148c253b11e','2023472024@student.uitm.edu.my');
Insert into SYSTEM.GUEST (GUESTID,FULLNAME,PHONENO,USERNAME,GPASSWORD,EMAIL) values (9,'KHAIRRUN ','0132145670','khai','scrypt:32768:8:1$ELGVphqaae0PjfEK$3b079850aa87781c42d825faf8e0dd7d6516e9dd573ed4fae53a99f994f1564dbb139452658e9c8e6c6caf48d0175f45059f2778b34704723379d3747dfcf061','khairrun@gmail.com');
--------------------------------------------------------
--  DDL for Index SYS_C008484
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008484" ON "SYSTEM"."ADMIN" ("ADMINID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008490
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008490" ON "SYSTEM"."BILL" ("BILLID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008487
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008487" ON "SYSTEM"."BOOKING" ("BOOKINGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008483
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008483" ON "SYSTEM"."GUEST" ("GUESTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_ADMIN_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_ADMIN_ID" 
BEFORE INSERT ON Admin
FOR EACH ROW
BEGIN
  :new.AdminID := seq_admin.NEXTVAL;
END;

/
ALTER TRIGGER "SYSTEM"."TRG_ADMIN_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BILL_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_BILL_ID" 
BEFORE INSERT ON Bill
FOR EACH ROW
BEGIN
  :new.BillID := seq_bill.NEXTVAL;
END;

/
ALTER TRIGGER "SYSTEM"."TRG_BILL_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BOOKING_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_BOOKING_ID" 
BEFORE INSERT ON Booking
FOR EACH ROW
BEGIN
  :new.BookingID := seq_booking.NEXTVAL;
END;

/
ALTER TRIGGER "SYSTEM"."TRG_BOOKING_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_GUEST_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_GUEST_ID" 
BEFORE INSERT ON GUEST
FOR EACH ROW
BEGIN
  SELECT GUEST_SEQ.NEXTVAL INTO :new.GUESTID FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_GUEST_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADMIN" ADD PRIMARY KEY ("ADMINID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BILL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BILL" ADD PRIMARY KEY ("BILLID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOKING" ADD PRIMARY KEY ("BOOKINGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUEST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GUEST" ADD PRIMARY KEY ("GUESTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BILL" ADD CONSTRAINT "FK_BILL_BOOKING" FOREIGN KEY ("BOOKINGID")
	  REFERENCES "SYSTEM"."BOOKING" ("BOOKINGID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKING
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOOKING" ADD CONSTRAINT "FK_BOOKING_GUEST" FOREIGN KEY ("GUESTID")
	  REFERENCES "SYSTEM"."GUEST" ("GUESTID") ENABLE;
  ALTER TABLE "SYSTEM"."BOOKING" ADD CONSTRAINT "FK_BOOKING_ADMIN" FOREIGN KEY ("ADMINID")
	  REFERENCES "SYSTEM"."ADMIN" ("ADMINID") ENABLE;
